# Secret to store the access variables to the Postgresql Database
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgresql-credentials
  namespace: {{.Release.Namespace}}
  labels:
    heritage: {{.Release.Service | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    release: {{.Release.Name | quote }}
  annotations:
    "helm.sh/created": {{.Release.Time.Seconds | quote }}
type: Opaque
data:
  username: {{ b64enc .Values.postgresqldb.credentials.username | quote }}
  password: {{ b64enc .Values.postgresqldb.credentials.password | quote }}

