###
#
# Global Variable for project
#
###

###
#
# Bench Container (wrk)
#
###
wrk: 
  replicaCount: 1
  image: williamyeh/wrk
  resources: 
    requests:
     cpu: 1000m
     memory: 2048Mi
    limits:
     cpu: 16000m
     memory: 16384Mi
  nodeSelector: {}
  timeout: 2s
  concurrency: 10
  duration: 30s
  threads: 5
  # pick nginx or varnish
  target: nginx
  file: 64b

###
#
# Serving Container (nginx)
#
###
sourceNginx: 
  replicaCount: 1
  image: nginx
  resources: 
    requests:
     cpu: 1000m
     memory: 8192Mi
    limits:
     cpu: 4000m
     memory: 16384Mi
  nodeSelector: 
    kubernetes.io/hostname: kontron-node01-cpu01
  hostPath: /varnish-data

###
#
# Cache Container (nginx)
#
###
cacheNginx: 
  replicaCount: 1
  image: nginx
  resources: 
    requests:
     cpu: 1000m
     memory: 8192Mi
    limits:
     cpu: 4000m
     memory: 16384Mi
  nodeSelector: 
    kubernetes.io/hostname: kontron-node07
  config: |-
    worker_processes  auto;
    worker_rlimit_nofile 1000000;
    error_log  /dev/stdout warn;
    pid        /var/run/nginxall.pid;
    events {
      worker_connections  1000000;
      use epoll;
      multi_accept on;
    }
    http {
      include                     /etc/nginx/mime.types;
      default_type                application/octet-stream;
      access_log                  off;
      sendfile                    on;
      server_tokens               off;
      keepalive_timeout           300;
      keepalive_requests          100000;
      tcp_nopush                  on;
      tcp_nodelay                 on;
      client_body_buffer_size     128k;
      client_header_buffer_size   1m;
      large_client_header_buffers 4 4k;
      output_buffers              1 32k;
      postpone_output             1460;
      open_file_cache             max=200000 inactive=20s;
      open_file_cache_valid       30s;
      open_file_cache_min_uses    2;
      open_file_cache_errors      on;
      proxy_cache_path /tmp/cache_all levels=1:2 keys_zone=STATIC:10m inactive=24h max_size=1g;
      server {
        listen 80;
        location / {
          proxy_pass        http://benchmark-source-nginx.default.svc.cluster.local/;
          proxy_cache       STATIC;
          proxy_cache_valid any 1d;
        }
      }
    }

###
#
# Cache Container (varnish)
#
###
varnish: 
  replicaCount: 1
  image: samnco/varnish
  resources: 
    requests:
     cpu: 1000m
     memory: 8192Mi
    limits:
     cpu: 4000m
     memory: 16384Mi
  nodeSelector: 
    kubernetes.io/hostname: kontron-node08
  command: ["/usr/sbin/varnishd", "-F", "-f", "/etc/varnish/default.vcl", "-s", "malloc,2048M", "-a", "0.0.0.0:80", "-a", "0.0.0.0:81,PROXY"]
  config: |-
    vcl 4.0;
    backend default {
        .host = "benchmark-source-nginx.default.svc.cluster.local";
        .port = "80";
    }
    sub vcl_recv {
    }
    sub vcl_backend_response {
        set beresp.ttl = 1d;
    }
    sub vcl_deliver {
        # remove these headers to make headers same
        unset resp.http.Via;
        unset resp.http.Age;
        unset resp.http.X-Varnish;
    }


