kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: docker-registry
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
  selector:
    matchLabels:
      nas: "registry"