kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: backup
  namespace: sistemas-internet
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  selector:
    matchLabels:
      nas: "backup"
