kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: backup
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  selector:
    matchLabels:
      location: "backup"
