apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "fullname" . }}
spec:
  capacity:
    storage: {{ .Values.persistence.size | quote }}
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ template "fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
    path: "/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "fullname" . }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
