apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-config
  namespace: {{.Release.Namespace}}
  labels:
    app: {{ template "fullname" . }}
    heritage: {{.Release.Service | quote }}
    chart: {{.Chart.Name}}-{{.Chart.Version}}
    release: {{ .Release.Name | quote }}
data:
  phoronix-test-suite.xml: |-
{{ .Values.config | indent 4 }}
