# This is the secret for the TLS encryption 
# Consumed by the ingress endpoint
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-tls-data
  namespace: {{ .Release.namespace }}
type: Opaque
data:
  tls.crt: {{ b64enc .Values.ingress.tls.certificate }}
  tls.key: {{ b64enc .Values.ingress.tls.key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-auth-data
  namespace: {{ .Release.namespace }}
type: Opaque
data:
  htpasswd: {{ b64enc .Values.service.htPasswd }}
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: {{ template "name" . }}-access
#   namespace: {{ .Release.namespace }}
# data:
#   .dockercfg: # Not sure this is needed at this point
# type: kubernetes.io/dockercfg
