# Type is a simple test differenciator
type: ktrn

# How many times do we run each benchmark AT THE SAME TIME. 
# Note that if this number exceeds the total number of GPUs and 
# the test is set to gpu mode, then some pods will not be scheduled
parallelism: 1

# Provide indications on resource quotas. Helps understand the profile of the app 
resources:
  requests:
    cpu: 100m
    memory: 8Gi
  limit:
    cpu: 100m
    memory: 32Gi

# Is this a GPU Benchmark? If true, inidicate the type of GPU nvidia or amd. Otherwise set to anything
gpuType: cpu

# Change this if you have several scripts
command: [ "/data/run-alpr.sh" ]

# Where to load storage from
storage:
  name: nfs-nfs

# If run in GPU mode, you must also change the library in the config file. 
# You can also change settings to understand the profile. 
openalprConfig: |-
  runtime_dir = ${CMAKE_INSTALL_PREFIX}/share/openalpr/runtime_data
  ocr_img_size_percent = 1.33333333
  state_id_img_size_percent = 2.0
  prewarp =
  max_plate_width_percent = 100
  max_plate_height_percent = 100
  detection_iteration_increase = 1.1
  detection_strictness = 3
  max_detection_input_width = 1280
  max_detection_input_height = 720
  ; lbpcpu    - default LBP-based detector uses the system CPU  
  ; lbpgpu    - LBP-based detector that uses Nvidia GPU to increase recognition speed.
  ; lbpopencl - LBP-based detector that uses OpenCL GPU to increase recognition speed.  Requires OpenCV 3.0
  ; morphcpu  - Experimental detector that detects white rectangles in an image.  Does not require training.
  detector = lbpcpu
  must_match_pattern = 0
  skip_detection = 0
  detection_mask_image = 
  analysis_count = 1
  contrast_detection_threshold = 0.3
  max_plate_angle_degrees = 15
  ocr_min_font_point = 6
  postprocess_min_confidence = 65
  postprocess_confidence_skip_level = 80
  debug_general         = 0
  debug_timing          = 0
  debug_detector        = 0
  debug_prewarp         = 0
  debug_state_id        = 0
  debug_plate_lines     = 0
  debug_plate_corners   = 0
  debug_char_segment    = 0
  debug_char_analysis   = 0
  debug_color_filter    = 0
  debug_ocr             = 0
  debug_postprocess     = 0
  debug_show_images     = 0
  debug_pause_on_frame  = 0
