apiVersion: v1
kind: Service
metadata:
  name: {{.Values.tensorboard.service.name | trunc 24 }}
  namespace: {{.Release.Namespace}}
  labels:
    app: {{.Values.tensorboard.service.name | trunc 24 }}
    heritage: {{.Release.Service | quote }}
    chart: {{.Chart.Name}}-{{.Chart.Version}}
    release: {{.Release.Name | quote }}
  annotations:
    "helm.sh/created": {{.Release.Time.Seconds | quote }}
spec:
  type: {{.Values.tensorboard.service.type | quote }}
  selector:
    app: {{.Values.tensorboard.service.name | trunc 24 }}
  ports:
  - name: http
    port: {{.Values.tensorboard.service.externalPort}}
    targetPort: {{.Values.tensorboard.service.internalPort}}
    protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tensorboard
spec:
  rules:
  - host: {{.Values.tensorboard.service.dns | trunc 24 }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{.Values.tensorboard.service.name | trunc 24 }}
          servicePort: {{.Values.tensorboard.service.externalPort}}
